# -*- coding: utf-8 -*-
"""Sql_Query_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWdC1eXVgZzvYn8JFuNDfnnSvVl2MJbf
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
{"role": "user", "content": "Who are you?"},
]
pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
{"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
messages,
add_generation_prompt=True,
tokenize=True,
return_dict=True,
return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio transformers torch black autopep8 reportlab requests

!pip uninstall -y gradio gradio-client huggingface_hub

!pip install gradio==4.44.0 huggingface_hub==0.23.5

!pip install gradio==3.50.2 huggingface_hub==0.16.4 reportlab==4.0.4 transformers torch black autopep8 requests

# First, uninstall and install a compatible Gradio version
!pip uninstall -y gradio
!pip install gradio==3.50.2

# Now run the complete code
import gradio as gr
from datetime import datetime
from pathlib import Path
import re
import urllib.parse

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

# ==============================
# GLOBAL STORAGE
# ==============================
query_history = []

# ==============================
# DATABASE SCHEMA
# ==============================
SCHEMA = {
    "users": {
        "id": "INTEGER PRIMARY KEY",
        "name": "TEXT",
        "email": "TEXT",
        "signup_date": "DATE",
        "age": "INTEGER",
        "country": "TEXT",
        "status": "TEXT",
    },
    "transactions": {
        "id": "INTEGER PRIMARY KEY",
        "user_id": "INTEGER",
        "amount": "DECIMAL",
        "date": "DATE",
        "category": "TEXT",
        "description": "TEXT"
    },
    "products": {
        "id": "INTEGER PRIMARY KEY",
        "name": "TEXT",
        "price": "DECIMAL",
        "category": "TEXT",
        "stock": "INTEGER"
    }
}

# ==============================
# SECURITY
# ==============================
DANGEROUS_KEYWORDS = ["DROP","DELETE","ALTER","TRUNCATE","INSERT","UPDATE","CREATE","REPLACE"]
DANGEROUS_CHARS = [";","--","/*","*/"]

def is_safe(text):
    text_upper = text.upper()

    for keyword in DANGEROUS_KEYWORDS:
        if keyword in text_upper:
            return False

    for char in DANGEROUS_CHARS:
        if char in text:
            return False

    return True

# ==============================
# ENHANCED SQL GENERATOR
# ==============================
def detect_table(query_text):
    query_lower = query_text.lower()

    if "transaction" in query_lower or "payment" in query_lower or "amount" in query_lower:
        return "transactions"
    elif "product" in query_lower or "item" in query_lower or "price" in query_lower:
        return "products"
    else:
        return "users"

def generate_sql(query_text):
    if not is_safe(query_text):
        return None, "Unsafe SQL detected"

    query_lower = query_text.lower()
    table = detect_table(query_text)

    # Start building SQL
    sql = f"SELECT * FROM {table}"
    conditions = []

    # ===== AMOUNT CONDITIONS =====
    amount_patterns = [
        (r'> (\d+)', '>'),
        (r'greater than (\d+)', '>'),
        (r'< (\d+)', '<'),
        (r'less than (\d+)', '<'),
        (r'>= (\d+)', '>='),
        (r'<= (\d+)', '<=')
    ]

    for pattern, operator in amount_patterns:
        match = re.search(pattern, query_lower)
        if match:
            if table == "transactions":
                conditions.append(f"amount {operator} {match.group(1)}")
            elif table == "products":
                conditions.append(f"price {operator} {match.group(1)}")
            break

    # ===== TIME CONDITIONS =====
    if "last week" in query_lower or "past week" in query_lower:
        if table == "users":
            conditions.append("signup_date >= DATE('now', '-7 days')")
        elif table == "transactions":
            conditions.append("date >= DATE('now', '-7 days')")
    elif "last month" in query_lower or "past month" in query_lower:
        if table == "users":
            conditions.append("signup_date >= DATE('now', '-1 month')")
        elif table == "transactions":
            conditions.append("date >= DATE('now', '-1 month')")
    elif "last 30 days" in query_lower:
        if table == "users":
            conditions.append("signup_date >= DATE('now', '-30 days')")
        elif table == "transactions":
            conditions.append("date >= DATE('now', '-30 days')")
    elif "today" in query_lower:
        if table == "users":
            conditions.append("DATE(signup_date) = DATE('now')")
        elif table == "transactions":
            conditions.append("DATE(date) = DATE('now')")

    # ===== STATUS CONDITIONS =====
    if "active" in query_lower and table == "users":
        conditions.append("status = 'active'")
    elif "inactive" in query_lower and table == "users":
        conditions.append("status = 'inactive'")

    # ===== COUNTRY CONDITIONS =====
    countries = ["usa", "uk", "canada", "australia", "india", "germany", "france"]
    for country in countries:
        if country in query_lower and table == "users":
            conditions.append(f"country = '{country.upper()}'")
            break

    # ===== CATEGORY CONDITIONS =====
    categories = ["electronics", "clothing", "food", "books", "furniture"]
    for category in categories:
        if category in query_lower and (table == "products" or table == "transactions"):
            conditions.append(f"category = '{category}'")
            break

    # ===== AGE CONDITIONS =====
    age_match = re.search(r'age (\d+)', query_lower)
    if age_match and table == "users":
        conditions.append(f"age = {age_match.group(1)}")

    # ===== ORDER BY =====
    order_clause = ""
    if "latest" in query_lower or "recent" in query_lower or "newest" in query_lower:
        if table == "users":
            order_clause = " ORDER BY signup_date DESC"
        elif table == "transactions":
            order_clause = " ORDER BY date DESC"
    elif "oldest" in query_lower:
        if table == "users":
            order_clause = " ORDER BY signup_date ASC"
        elif table == "transactions":
            order_clause = " ORDER BY date ASC"
    elif "highest" in query_lower or "largest" in query_lower:
        if table == "transactions":
            order_clause = " ORDER BY amount DESC"
        elif table == "products":
            order_clause = " ORDER BY price DESC"
    elif "lowest" in query_lower or "smallest" in query_lower:
        if table == "transactions":
            order_clause = " ORDER BY amount ASC"
        elif table == "products":
            order_clause = " ORDER BY price ASC"

    # Build the final SQL
    if conditions:
        sql += " WHERE " + " AND ".join(conditions)

    sql += order_clause

    # ===== LIMIT =====
    limit_match = re.search(r'limit (\d+)', query_lower)
    if limit_match:
        sql += f" LIMIT {limit_match.group(1)}"
    else:
        # Check for implicit limits
        if "top 10" in query_lower or "first 10" in query_lower:
            sql += " LIMIT 10"
        elif "top 5" in query_lower or "first 5" in query_lower:
            sql += " LIMIT 5"
        elif "all" in query_lower:
            sql += " LIMIT 1000"
        else:
            sql += " LIMIT 50"  # Default limit

    return sql, f"SQL generated for {table} table"

# ==============================
# CHAT PROCESS
# ==============================
def process_query(user_query, chat_history):
    global query_history

    if not user_query or not user_query.strip():
        chat_history.append(("", "⚠️ Please enter a query"))
        return chat_history

    sql_query, message = generate_sql(user_query)

    if sql_query is None:
        response = "❌ " + message
    else:
        response = "✅ SQL GENERATED\n\n```sql\n" + sql_query + "\n```\n\n📝 " + message

        query_history.append({
            "user": user_query,
            "sql": sql_query,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        })

    chat_history.append((user_query, response))
    return chat_history

# ==============================
# CLEAR CHAT
# ==============================
def clear_chat():
    global query_history
    query_history = []
    return []

# ==============================
# DOWNLOAD PDF
# ==============================
def download_pdf():
    if not query_history:
        return "No queries", None

    filename = f"sql_queries_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("SQL Query Report", styles["Heading1"]))
    story.append(Spacer(1, 20))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    story.append(Spacer(1, 20))

    for i, q in enumerate(query_history, 1):
        story.append(Paragraph(f"Query #{i}", styles["Heading2"]))
        story.append(Paragraph(f"User: {q['user']}", styles["Normal"]))
        story.append(Paragraph(f"SQL: {q['sql']}", styles["Normal"]))
        story.append(Paragraph(f"Time: {q['timestamp']}", styles["Normal"]))
        story.append(Spacer(1, 10))

    doc.build(story)
    return "PDF Generated", filename

# ==============================
# DOWNLOAD TXT
# ==============================
def download_txt():
    if not query_history:
        return "No queries", None

    filename = f"sql_queries_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    content = f"SQL QUERY HISTORY\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n{'='*50}\n\n"

    for i, q in enumerate(query_history, 1):
        content += f"Query #{i}\n{'-'*30}\n"
        content += f"User: {q['user']}\n"
        content += f"SQL: {q['sql']}\n"
        content += f"Time: {q['timestamp']}\n\n"

    Path(filename).write_text(content)
    return "TXT Generated", filename

# ==============================
# WHATSAPP LINK
# ==============================
def generate_whatsapp_link():
    if not query_history:
        return "No queries to share"

    message = "📊 SQL Queries:\n\n"
    for q in query_history[-5:]:
        message += f"• {q['user']}\n  → {q['sql']}\n\n"

    encoded = urllib.parse.quote(message)
    return f"https://wa.me/?text={encoded}"


custom_css = """
    /* Main container - Clean white with subtle gradient */
    .gradio-container {
        background: linear-gradient(135deg, #f5f7fa 0%, #e9ecef 100%) !important;
    }

    .gradio-container .main {
        background: linear-gradient(135deg, #f5f7fa 0%, #e9ecef 100%) !important;
        padding: 20px !important;
    }

    /* Headers - Professional navy */
    h1 {
        color: #2c3e50 !important;
        font-size: 2.3em !important;
        font-weight: 500 !important;
        border-bottom: 3px solid #3498db !important;
        display: inline-block !important;
        padding-bottom: 10px !important;
        margin-bottom: 20px !important;
    }

    /* Chatbot styling - Clean and minimal */
    .gradio-chatbot {
        border: 1px solid #dee2e6 !important;
        border-radius: 8px !important;
        background: white !important;
        box-shadow: 0 2px 4px rgba(0,0,0,0.02) !important;
    }

    /* User message bubble */
    .user {
        background: #e3f2fd !important;
        color: #1e3c5c !important;
        border-radius: 18px 18px 4px 18px !important;
        padding: 12px 16px !important;
        margin: 8px !important;
        box-shadow: 0 1px 2px rgba(0,0,0,0.05) !important;
        font-size: 14px !important;
    }

    /* Bot message bubble */
    .bot {
        background: #f8f9fa !important;
        color: #2c3e50 !important;
        border-radius: 18px 18px 18px 4px !important;
        padding: 12px 16px !important;
        margin: 8px !important;
        box-shadow: 0 1px 2px rgba(0,0,0,0.05) !important;
        font-size: 14px !important;
    }

    /* SQL code block inside bot message - FIXED VISIBILITY */
    .bot pre {
        background: #2d2d2d !important;
        color: #f8f8f2 !important;
        border-radius: 6px !important;
        padding: 12px !important;
        margin: 10px 0 !important;
        border: 1px solid #444 !important;
        font-family: 'Courier New', monospace !important;
        font-size: 13px !important;
        overflow-x: auto !important;
    }

    /* SQL code text */
    .bot code {
        color: #f8f8f2 !important;
        font-family: 'Courier New', monospace !important;
    }

    /* Regular text in bot message */
    .bot p {
        color: #2c3e50 !important;
        margin: 5px 0 !important;
    }

    /* Bot message header */
    .bot strong {
        color: #2c3e50 !important;
    }

    /* Emoji in bot message */
    .bot .emoji {
        font-size: 16px !important;
    }

    /* Input box */
    input[type="text"], textarea {
        border: 1px solid #dee2e6 !important;
        border-radius: 8px !important;
        padding: 12px 16px !important;
        font-size: 14px !important;
        transition: all 0.2s ease !important;
        background: white !important;
    }

    input[type="text"]:focus, textarea:focus {
        border-color: #3498db !important;
        box-shadow: 0 0 0 3px rgba(52,152,219,0.1) !important;
        outline: none !important;
    }

    /* Buttons */
    button {
        background: #3498db !important;
        color: white !important;
        border: none !important;
        border-radius: 6px !important;
        padding: 10px 20px !important;
        font-size: 14px !important;
        font-weight: 500 !important;
        cursor: pointer !important;
        transition: all 0.2s ease !important;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05) !important;
    }

    button:hover {
        background: #2980b9 !important;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1) !important;
    }

    /* Primary button */
    .primary, button.primary {
        background: #2c3e50 !important;
    }

    .primary:hover, button.primary:hover {
        background: #1e2b37 !important;
    }

    /* Secondary buttons */
    .secondary, button.secondary {
        background: #ecf0f1 !important;
        color: #2c3e50 !important;
        border: 1px solid #dee2e6 !important;
    }

    .secondary:hover, button.secondary:hover {
        background: #dee2e6 !important;
    }

    /* Status text */
    .status, textarea[class*="status"] {
        color: #2c3e50 !important;
        background: #f8f9fa !important;
        border: 1px solid #dee2e6 !important;
        padding: 10px !important;
        border-radius: 6px !important;
        font-size: 13px !important;
    }

    /* File outputs */
    .file-output, .gr-file {
        background: white !important;
        border: 1px solid #dee2e6 !important;
        border-radius: 6px !important;
        padding: 10px !important;
    }

    /* Footer */
    .footer {
        color: #6c757d !important;
        text-align: center !important;
        padding: 20px !important;
        margin-top: 30px !important;
        border-top: 1px solid #dee2e6 !important;
        font-size: 13px !important;
    }

    /* Examples section */
    .examples {
        background: white !important;
        border: 1px solid #dee2e6 !important;
        border-radius: 8px !important;
        padding: 15px !important;
        margin: 15px 0 !important;
    }

    /* Example items */
    .examples button {
        background: #f8f9fa !important;
        color: #2c3e50 !important;
        border: 1px solid #dee2e6 !important;
        padding: 8px 12px !important;
        margin: 5px !important;
        font-size: 13px !important;
    }

    .examples button:hover {
        background: #e3f2fd !important;
        border-color: #3498db !important;
    }

    /* Labels */
    label {
        color: #2c3e50 !important;
        font-weight: 500 !important;
        font-size: 13px !important;
        margin-bottom: 5px !important;
    }

    /* Custom scrollbar */
    ::-webkit-scrollbar {
        width: 8px !important;
        height: 8px !important;
    }

    ::-webkit-scrollbar-track {
        background: #f1f1f1 !important;
    }

    ::-webkit-scrollbar-thumb {
        background: #c1c1c1 !important;
        border-radius: 4px !important;
    }

    ::-webkit-scrollbar-thumb:hover {
        background: #a8a8a8 !important;
    }

    /* Markdown text */
    .markdown {
        color: #2c3e50 !important;
    }

    /* Links */
    a {
        color: #3498db !important;
        text-decoration: none !important;
    }

    a:hover {
        text-decoration: underline !important;
    }
"""

# ==============================
# GRADIO INTERFACE (rest of the code remains the same)
# ==============================
with gr.Blocks(css=custom_css) as demo:
    # Header
    gr.Markdown("""
    # Natural Language → SQL Generator
    Convert plain English to SQL queries
    """)

    with gr.Row():
        with gr.Column(scale=2):
            # Chatbot
            chatbot = gr.Chatbot(height=400, elem_id="chatbot")

    # Input section
    with gr.Row():
        with gr.Column(scale=4):
            query_input = gr.Textbox(
                label="Your Request",
                placeholder="Example: Find transactions greater than 500 from last week",
                lines=2
            )

        with gr.Column(scale=1):
            send_btn = gr.Button("Generate SQL", variant="primary", elem_classes="primary")

    # Examples section
    gr.Examples(
        examples=[
            ["Find transactions greater than 500 from last week"],
            ["Show active users who signed up last month"],
            ["Get products with price less than 100"],
            ["Show latest 10 transactions from USA"],
            ["Find electronics products"],
            ["Show users older than 25"]
        ],
        inputs=query_input
    )

    # Action buttons
    with gr.Row():
        clear_btn = gr.Button("Clear Chat", variant="secondary", elem_classes="secondary")

    # Export section
    gr.Markdown("## Export Options")

    with gr.Row():
        pdf_btn = gr.Button("📄 PDF", variant="secondary", elem_classes="secondary")
        txt_btn = gr.Button("📝 TXT", variant="secondary", elem_classes="secondary")
        share_btn = gr.Button("📱 WhatsApp", variant="secondary", elem_classes="secondary")

    # Status and outputs
    export_status = gr.Textbox(label="Status", elem_classes="status")

    with gr.Row():
        pdf_file = gr.File(label="PDF Download")
        txt_file = gr.File(label="TXT Download")

    share_output = gr.Textbox(label="WhatsApp Link", elem_classes="status")

    # Event handlers
    send_btn.click(
        process_query,
        inputs=[query_input, chatbot],
        outputs=[chatbot]
    ).then(
        lambda: "", None, query_input
    )

    query_input.submit(
        process_query,
        inputs=[query_input, chatbot],
        outputs=[chatbot]
    ).then(
        lambda: "", None, query_input
    )

    clear_btn.click(clear_chat, outputs=[chatbot])

    pdf_btn.click(download_pdf, outputs=[export_status, pdf_file])
    txt_btn.click(download_txt, outputs=[export_status, txt_file])
    share_btn.click(generate_whatsapp_link, outputs=[share_output])

    # Footer
    gr.Markdown("""
    ---
    ⚠️ All inputs are scanned for dangerous SQL keywords
    © 2024 SQL Generator
    """)

# ==============================
# LAUNCH
# ==============================
if __name__ == "__main__":
    print("🚀 Starting SQL Generator...")
    print("="*50)
    demo.launch(share=True, show_error=True, show_api=False)